apply plugin: 'com.android.application'

android {
    compileSdkVersion 29

    defaultConfig {
        applicationId 'com.era.probe2'
        minSdkVersion 23
        targetSdkVersion 29
        versionCode 1
        versionName '0.1-probe2'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
